# Designed by Junbo Zhao
# 12/23/2013
# This is a simple demo, training and testing the adaboost classifier

from numpy import *
import data
import adaboost

# The following data files are only used to show you how this program works.
# The two files are generated by function randomData()

# It is better to use your own data to see the power of adaboost!
# Face recognition problems are good for using adaboost.

trainData,label = data.readData('train.txt','train')
#trainData,label = data.loadSimpleData()
testData = data.readData('test.txt','test')
classifier = adaboost.train(trainData,label,150)
adaboost.test(testData,classifier)

input()
